Added support for PHP 8.2
researchgate/avro-php pull request #9
Opened 2023-03-27 16:43 UTC by inri13666

2023-03-27 20:08 UTC, stefanhoth commented
@inri13666 Thank you for your contribution. Would you mind rebasing it against master so we can also run the (new) checks of PHP 8.2. Thank you!

2023-03-29 10:51 UTC, inri13666 commented
@stefanhoth seems rebase is done

2023-04-03 08:08 UTC, stefanhoth commented
@mdio @mustafah15 Any worries about this one?

2023-04-04 07:51 UTC, mdio commented
In `schema.php` there are only 3 dynamically created properties which can (and in my opinion, should) be specified.
I think that would be the cleaner approach compared to allowing these dynamic properties to exist.

`data_file.php` and `protocol.php` have 2 dynamic properties each that would also need to be declared.

Also `DataFileTest.php` has a usage of `strftime()` which is deprecated since PHP 8.1 and should be replaced.

This PR should be a good point of reference: https://github.com/flix-tech/avro-php/pull/19/files

@inri13666 would you be okay with adjusting your PR accordingly?

2023-04-04 07:52 UTC, mdio requested changes
In `schema.php` there are only 3 dynamically created properties which can (and in my opinion, should) be specified.
I think that would be the cleaner approach compared to allowing these dynamic properties to exist.

`data_file.php` and `protocol.php` have 2 dynamic properties each that would also need to be declared.

Also `DataFileTest.php` has a usage of `strftime()` which is deprecated since PHP 8.1 and should be replaced.

This PR should be a good point of reference: https://github.com/flix-tech/avro-php/pull/19/files

@inri13666 would you be okay with adjusting your PR accordingly?

2023-10-26 11:48 UTC, mdio commented
Thank you for your effort!
We've decided to close this project in favour of [flix-tech/avro-php](https://github.com/flix-tech/avro-php) which already has PHP 8.2 support.

2023-10-26 11:48 UTC, closed without merging